services:
 - docker
install:
  - docker build -t unifi .
  - docker run -d -p 8443:8443 -e RUNAS_UID0=true -e PKGURL=https://dl.ubnt.com/unifi/5.7.23/unifi_sysvinit_all.deb --name unifi unifi 
script:
  - docker ps | grep -q unifi
  - docker logs unifi
  - sleep 10 && curl -kILs --fail https://127.0.0.1:8443 || exit 1
